<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250930164742 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE appointment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, proposed_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, confirmed_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status VARCHAR(50) NOT NULL, location VARCHAR(255) DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, tree_request_id INT NOT NULL, citizen_id INT NOT NULL, agent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FE38F844B96D40A4 ON appointment (tree_request_id)');
        $this->addSql('CREATE INDEX IDX_FE38F844A63C3C2E ON appointment (citizen_id)');
        $this->addSql('CREATE INDEX IDX_FE38F8443414710B ON appointment (agent_id)');
        $this->addSql('CREATE TABLE photo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, filename VARCHAR(255) NOT NULL, original_name VARCHAR(255) NOT NULL, path VARCHAR(255) NOT NULL, mime_type VARCHAR(100) NOT NULL, size INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tree_id INT DEFAULT NULL, tree_request_id INT DEFAULT NULL, uploaded_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_14B7841878B64A2 ON photo (tree_id)');
        $this->addSql('CREATE INDEX IDX_14B78418B96D40A4 ON photo (tree_request_id)');
        $this->addSql('CREATE INDEX IDX_14B78418A2B28FE8 ON photo (uploaded_by_id)');
        $this->addSql('CREATE TABLE tree (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, latitude DOUBLE PRECISION NOT NULL, longitude DOUBLE PRECISION NOT NULL, age INT DEFAULT NULL, plantation_date DATE DEFAULT NULL, height DOUBLE PRECISION DEFAULT NULL, diameter DOUBLE PRECISION DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, tree_type_id INT NOT NULL, status_id INT NOT NULL, contributor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B73E5EDCFCB2E8E ON tree (tree_type_id)');
        $this->addSql('CREATE INDEX IDX_B73E5EDC6BF700BD ON tree (status_id)');
        $this->addSql('CREATE INDEX IDX_B73E5EDC7A19A357 ON tree (contributor_id)');
        $this->addSql('CREATE TABLE tree_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, latitude DOUBLE PRECISION NOT NULL, longitude DOUBLE PRECISION NOT NULL, estimated_age INT DEFAULT NULL, description TEXT DEFAULT NULL, status VARCHAR(50) NOT NULL, needs_appointment BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, processed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, citizen_id INT NOT NULL, proposed_tree_type_id INT DEFAULT NULL, validated_tree_id INT DEFAULT NULL, processed_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F1102D82A63C3C2E ON tree_request (citizen_id)');
        $this->addSql('CREATE INDEX IDX_F1102D82705B988F ON tree_request (proposed_tree_type_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F1102D82ABE0FC4A ON tree_request (validated_tree_id)');
        $this->addSql('CREATE INDEX IDX_F1102D822FFD4FD3 ON tree_request (processed_by_id)');
        $this->addSql('CREATE TABLE tree_status (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, label VARCHAR(50) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tree_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, scientific_name VARCHAR(255) NOT NULL, common_name VARCHAR(255) NOT NULL, max_carbon_storage DOUBLE PRECISION DEFAULT NULL, carbon_growth_coefficient DOUBLE PRECISION DEFAULT NULL, max_cool_zone DOUBLE PRECISION DEFAULT NULL, cool_zone_growth_coefficient DOUBLE PRECISION DEFAULT NULL, maturity_age INT DEFAULT NULL, allergy_potential VARCHAR(50) DEFAULT NULL, resilience VARCHAR(50) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F844B96D40A4 FOREIGN KEY (tree_request_id) REFERENCES tree_request (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F844A63C3C2E FOREIGN KEY (citizen_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F8443414710B FOREIGN KEY (agent_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE photo ADD CONSTRAINT FK_14B7841878B64A2 FOREIGN KEY (tree_id) REFERENCES tree (id)');
        $this->addSql('ALTER TABLE photo ADD CONSTRAINT FK_14B78418B96D40A4 FOREIGN KEY (tree_request_id) REFERENCES tree_request (id)');
        $this->addSql('ALTER TABLE photo ADD CONSTRAINT FK_14B78418A2B28FE8 FOREIGN KEY (uploaded_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tree ADD CONSTRAINT FK_B73E5EDCFCB2E8E FOREIGN KEY (tree_type_id) REFERENCES tree_type (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tree ADD CONSTRAINT FK_B73E5EDC6BF700BD FOREIGN KEY (status_id) REFERENCES tree_status (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tree ADD CONSTRAINT FK_B73E5EDC7A19A357 FOREIGN KEY (contributor_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE tree_request ADD CONSTRAINT FK_F1102D82A63C3C2E FOREIGN KEY (citizen_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tree_request ADD CONSTRAINT FK_F1102D82705B988F FOREIGN KEY (proposed_tree_type_id) REFERENCES tree_type (id)');
        $this->addSql('ALTER TABLE tree_request ADD CONSTRAINT FK_F1102D82ABE0FC4A FOREIGN KEY (validated_tree_id) REFERENCES tree (id)');
        $this->addSql('ALTER TABLE tree_request ADD CONSTRAINT FK_F1102D822FFD4FD3 FOREIGN KEY (processed_by_id) REFERENCES "user" (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE appointment DROP CONSTRAINT FK_FE38F844B96D40A4');
        $this->addSql('ALTER TABLE appointment DROP CONSTRAINT FK_FE38F844A63C3C2E');
        $this->addSql('ALTER TABLE appointment DROP CONSTRAINT FK_FE38F8443414710B');
        $this->addSql('ALTER TABLE photo DROP CONSTRAINT FK_14B7841878B64A2');
        $this->addSql('ALTER TABLE photo DROP CONSTRAINT FK_14B78418B96D40A4');
        $this->addSql('ALTER TABLE photo DROP CONSTRAINT FK_14B78418A2B28FE8');
        $this->addSql('ALTER TABLE tree DROP CONSTRAINT FK_B73E5EDCFCB2E8E');
        $this->addSql('ALTER TABLE tree DROP CONSTRAINT FK_B73E5EDC6BF700BD');
        $this->addSql('ALTER TABLE tree DROP CONSTRAINT FK_B73E5EDC7A19A357');
        $this->addSql('ALTER TABLE tree_request DROP CONSTRAINT FK_F1102D82A63C3C2E');
        $this->addSql('ALTER TABLE tree_request DROP CONSTRAINT FK_F1102D82705B988F');
        $this->addSql('ALTER TABLE tree_request DROP CONSTRAINT FK_F1102D82ABE0FC4A');
        $this->addSql('ALTER TABLE tree_request DROP CONSTRAINT FK_F1102D822FFD4FD3');
        $this->addSql('DROP TABLE appointment');
        $this->addSql('DROP TABLE photo');
        $this->addSql('DROP TABLE tree');
        $this->addSql('DROP TABLE tree_request');
        $this->addSql('DROP TABLE tree_status');
        $this->addSql('DROP TABLE tree_type');
    }
}
